### ISSUE TITLE
Initialize Help onLoad

### ISSUE THREAD

**Issue by jmdye** [McShelby/reveal-helpbutton#1]
Feature Request: Please consider adding a capability to initialize the help button onload. Even though the help button is present in the bottom right corner, it would be useful to raise the help overlay immediately when the presentation loads initially.

**Comment by McShelby** [comment]
I am not quite sure about this feature. In the end, revealjs is still meant as a presentation framework and should show off that fact. If the help overlay would be displayed initially, it would hide the signature opening slide.

How do you think such a feature would help. Whats the use case scenario?

**Comment by jmdye** [comment]
Well, I agree that revealjs is meant as a presentation framework. However, the status quo for presentations is powerpoint and when end users that consume the presentation are given a link to a revealjs presentation the first time, usually they can figure out the left/down/up/right interactions pretty quickly. 

However, they typically don't know about the other controls or keyboard shortcuts (home, end, B, F, ESC/O, Ctrl-Shift-F). The help button you created helps them discover that pretty well. I just think an option to show that help overlay when the presentation is loaded the first time would also be helpful. Thanks for considering.

**Comment by McShelby** [comment]
Decided against implementing this. A user can easily achieve this by using reveals API. Hiding a slide on intial viewing would annoy all users that are familiar with reveal.
